apiVersion: v1
kind: Service
metadata:
  name: laravel-loadbalancer
  namespace: laravel-app-namespace
spec:
  type: LoadBalancer
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80